version: '2.2'
services:
  dnf:
    image: scjtqs/dnf-centos5
    container_name: dnf
    hostname: dnf
    privileged: true
    tty: true
    stdin_open: true
    shm_size: 8g
    oom_kill_disable: true
    mem_limit: 8g
    network_mode: host
    depends_on:
      - db
    environment:
      # DB_HOST 如果你是外部db修改这里的db配置吧
      - DB_HOST=127.0.0.1
      #添加你的公网Ip，如果处于nat网络中，请自行做好穿透
      - PublicIp=192.168.1.106
      - UDP_IP=192.168.1.106
      - DB_USER=game  #数据库的用户名
      - DB_PASS=uu5!^%jg  #数据库密码
      - DB_KEY=20e35501e56fcedbe8b10c1f8bc3595be8b10c1f8bc3595b  #数据库密码对应的密文. 可以用tea.php 计算。
    volumes:
#      - ./db:/home/data/              #数据库文件
      - ./Script.pvf:/src/Script.pvf  #你自己的pvf文件
      - ./df_game_r:/src/df_game_r  #等级补丁
      - ./run.sh:/root/run.sh      #可以自定义的启动脚本（主要是自己开频道用）
      - ./tongyi-5.8/Config.ini:/root/Config.ini

  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - TZ=Asia/Shanghai
    network_mode: host
    shm_size: 8g
    oom_kill_disable: true
    mem_limit: 8g
    command:
#      --character-set-server=utf8
#      --collation-server=utf8_general_ci
#      --lower_case_table_names=1
      --max_allowed_packet=20M
      --table_cache=64
      --sort_buffer_size=512K
      --net_buffer_length=8K
      --read_buffer_size=256K
      --read_rnd_buffer_size=512K
      --myisam_sort_buffer_size=8M
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql